<?php
return ['messages'=>['<p data-renderer-start-pos="102"> Al suscribirte, no solo tendrás <strong>acceso prioritario</strong> a las cositas que sacaré pronto, sino que también contarás con <strong data-renderer-mark="true">descuentos exclusivos.</strong></p><h5 data-renderer-start-pos="102"> </h5><h5 data-renderer-start-pos="102"><strong>¡Solo para miembros de la newsletter!</strong></h5>'=>'<p data-renderer-start-pos="102"> By subscribing, you\'ll not only get <strong>priority access</strong> to upcoming goodies, but you\'ll also get<strong data-renderer-mark="true"> exclusive discounts.</strong></p><h5 data-renderer-start-pos="102"> </h5><h5 data-renderer-start-pos="102"><strong>For newsletter members only!</strong></h5>','<p data-renderer-start-pos="674">Únete a una comunidad que celebra el crecimiento personal a través de la fotografía íntima.</p>'=>'<p data-renderer-start-pos="674">Join a community that celebrates personal growth through intimate photography.</p>','<ul class="ak-ul" data-indent-level="1"><li><p data-renderer-start-pos="334"><strong data-renderer-mark="true">Acceso Exclusivo</strong>: Sé el primero en saber todo lo que se viene.</p></li><li><p data-renderer-start-pos="400"><strong data-renderer-mark="true">Descuentos:</strong> Solo por formar parte, tendrás descuentos.</p></li><li><p data-renderer-start-pos="469"><strong data-renderer-mark="true">Contenido único</strong>: Consejos, anécdotas y recursos exclusivos.</p></li><li><p data-renderer-start-pos="469"><strong>Blog:</strong> Recibe notificaciones cuando suba nuevo contenido a mi blog.</p></li><li><strong data-renderer-mark="true">Inspiración y creatividad</strong>: Potencia tus habilidades en fotografía íntima y creatividad.</li></ul>'=>'<ul class="ak-ul" data-indent-level="1"><li><p data-renderer-start-pos="334"><strong data-renderer-mark="true">Exclusive Access:</strong> Be the first to know everything that\'s coming.</p></li><li><p data-renderer-start-pos="400"><strong data-renderer-mark="true">Discounts</strong>: Just for being a part of it, you\'ll get discounts.</p></li><li><p data-renderer-start-pos="469"><strong data-renderer-mark="true">Unique Content</strong>: Exclusive tips, anecdotes, and resources.</p></li><li><strong>Blog</strong>: Receive notifications when I upload new content to my blog.</li><li><p data-renderer-start-pos="570"><strong data-renderer-mark="true">Inspiration and Creativity</strong>: Boost your intimate photography and creativity skills.</p></li></ul>','Descubre el arte de capturar la esencia
'=>'Discover the art of capturing the essence
','Escríbeme a hola@marianaerato.com
'=>'Write to me at hola@marianaerato.com
','O sígueme en RRSS'=>'Or follow me on social media','Se parte de algo especial'=>'Be part of something special','Suscribirme'=>'Subscribe','Suscríbete'=>'Subscribe','editor-text-editor-2278adb'=>'<p data-renderer-start-pos="674">Join a community that celebrates personal growth through intimate photography.</p>','editor-text-editor-4af7550'=>'<p data-renderer-start-pos="102"> By subscribing, you\'ll not only get <strong>priority access</strong> to upcoming goodies, but you\'ll also get<strong data-renderer-mark="true"> exclusive discounts.</strong></p><h5 data-renderer-start-pos="102"> </h5><h5 data-renderer-start-pos="102"><strong>For newsletter members only!</strong></h5>','editor-text-editor-dcdc38d'=>'<ul class="ak-ul" data-indent-level="1"><li><p data-renderer-start-pos="334"><strong data-renderer-mark="true">Exclusive Access:</strong> Be the first to know everything that\'s coming.</p></li><li><p data-renderer-start-pos="400"><strong data-renderer-mark="true">Discounts</strong>: Just for being a part of it, you\'ll get discounts.</p></li><li><p data-renderer-start-pos="469"><strong data-renderer-mark="true">Unique Content</strong>: Exclusive tips, anecdotes, and resources.</p></li><li><strong>Blog</strong>: Receive notifications when I upload new content to my blog.</li><li><p data-renderer-start-pos="570"><strong data-renderer-mark="true">Inspiration and Creativity</strong>: Boost your intimate photography and creativity skills.</p></li></ul>','text-button-0ec170e'=>'Subscribe','text-button-5e6e5d9'=>'Subscribe','title-heading-2e81ea7'=>'Questions or doubts?','title-heading-2f35888'=>'Discover the art of capturing the essence
','title-heading-3b83b15'=>'Why subscribe?
','title-heading-507a3c2'=>'Write to me at hola@marianaerato.com
','title-heading-79ca820'=>'Join my Intimate Photography community!
','title-heading-d278c5f'=>'Don\'t miss it!
','title-heading-de7ee80'=>'Be part of something special','title-heading-f5b15d1'=>'Or follow me on social media','¡No te lo pierdas!
'=>'Don\'t miss it!
','¡Únete a mi comunidad de Fotografía Íntima!
'=>'Join my Intimate Photography community!
','¿Por qué suscribirte?
'=>'Why subscribe?
','¿Preguntas o dudas?'=>'Questions or doubts?']];
