<?php

namespace App\Hooks\Admin;

class Settings
{
    public function init(): void
    {
        add_action('acf/init', [$this, 'acf_init']);
        add_action('acf/include_fields', [$this, 'acf_include_fields']);
    }

    public function acf_init(): void
    {
        if (!function_exists('acf_add_options_page')) {
            return;
        }
        acf_add_options_page([
            'page_title' => __('Mariana Erato', APP_THEME_DOMAIN),
            'menu_slug' => 'mariana-erato',
            'parent_slug' => 'options-general.php',
            'position' => 0,
            'redirect' => false,
        ]);
    }

    public function acf_include_fields(): void
    {
        if (!function_exists('acf_add_local_field_group')) {
            return;
        }

        acf_add_local_field_group([
            'key' => 'group_67910896cb2dc',
            'title' => __('Settings', APP_THEME_DOMAIN),
            'fields' => [
                [
                    'key' => 'field_67aa48f441f4a',
                    'label' => __('Store', APP_THEME_DOMAIN),
                    'name' => '',
                    'aria-label' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'wpml_cf_preferences' => 1,
                    'placement' => 'left',
                    'endpoint' => 0,
                    'selected' => 0,
                ],
                [
                    'key' => 'field_67910897f53f7',
                    'label' => __('Buy post text', APP_THEME_DOMAIN),
                    'name' => 'buy_this_post_text',
                    'aria-label' => '',
                    'type' => 'textarea',
                    'instructions' => __('Wildcard %s will be replaced by product price.', APP_THEME_DOMAIN),
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'wpml_cf_preferences' => 2,
                    'default_value' => __('Compra este post por %s', APP_THEME_DOMAIN),
                    'maxlength' => 100,
                    'allow_in_bindings' => 0,
                    'rows' => 3,
                    'placeholder' => __('Compra este post por %s', APP_THEME_DOMAIN),
                    'new_lines' => '',
                ],
                [
                    'key' => 'field_67aa490641f4b',
                    'label' => __('Blog', APP_THEME_DOMAIN),
                    'name' => '',
                    'aria-label' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'wpml_cf_preferences' => 1,
                    'placement' => 'left',
                    'endpoint' => 0,
                    'selected' => 0,
                ],
                [
                    'key' => 'field_67aa491241f4c',
                    'label' => __('Appeals text', APP_THEME_DOMAIN),
                    'name' => 'appeals_text',
                    'aria-label' => '',
                    'type' => 'wysiwyg',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'wpml_cf_preferences' => 2,
                    'default_value' => '',
                    'allow_in_bindings' => 0,
                    'tabs' => 'all',
                    'toolbar' => 'full',
                    'media_upload' => 1,
                    'delay' => 0,
                ],
                [
                    'key' => 'field_67aa493141f4d',
                    'label' => __('Complaints text', APP_THEME_DOMAIN),
                    'name' => 'complaints_text',
                    'aria-label' => '',
                    'type' => 'wysiwyg',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'wpml_cf_preferences' => 2,
                    'default_value' => '',
                    'allow_in_bindings' => 0,
                    'tabs' => 'all',
                    'toolbar' => 'full',
                    'media_upload' => 1,
                    'delay' => 0,
                ],
                [
                    'key' => 'field_63hdndf949068si3b6',
                    'label' => __('Categories & tags', APP_THEME_DOMAIN),
                    'name' => '',
                    'aria-label' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'wpml_cf_preferences' => 1,
                    'placement' => 'left',
                    'endpoint' => 0,
                    'selected' => 0,
                ],
                [
                    'key' => 'field_8493h92kshufd7',
                    'label' => __('Sponsorship product category', APP_THEME_DOMAIN),
                    'name' => 'subscription_sponsorship_product_category',
                    'aria-label' => '',
                    'type' => 'taxonomy',
                    'taxonomy' => 'product_cat',
                    'return_format' => 'id',
                    'add_term' => 1,
                    'instructions' => __('Products in this category will be used as sponsorship.', APP_THEME_DOMAIN),
                    'save_terms' => 0,
                    'load_terms' => 0,
                    'field_type' => 'select',
                    'allow_null' => 0,
                    'allow_in_bindings' => 0,
                    'bidirectional' => 0,
                    'multiple' => 0,
                    'wrapper' => [
                        'width' => '50%',
                        'class' => '',
                        'id' => '',
                    ],
                ],
                [
                    'key' => 'field_64jh47892kshufd7',
                    'label' => __('Free post category', APP_THEME_DOMAIN),
                    'name' => 'free_post_category',
                    'aria-label' => '',
                    'type' => 'taxonomy',
                    'taxonomy' => 'category',
                    'instructions' => __('Posts in this category will be free and not require purchase.', APP_THEME_DOMAIN),
                    'return_format' => 'id',
                    'add_term' => 1,
                    'save_terms' => 0,
                    'load_terms' => 0,
                    'field_type' => 'select',
                    'allow_null' => 0,
                    'allow_in_bindings' => 0,
                    'bidirectional' => 0,
                    'multiple' => 0,
                    'wrapper' => [
                        'width' => '50%',
                        'class' => '',
                        'id' => '',
                    ],
                ],
                [
                    'key' => 'field_64jh4jfhg8643hfd7',
                    'label' => __('Paid post category', APP_THEME_DOMAIN),
                    'name' => 'paid_post_category',
                    'aria-label' => '',
                    'type' => 'taxonomy',
                    'taxonomy' => 'category',
                    'instructions' => __('Posts in this category will require purchase to access.', APP_THEME_DOMAIN),
                    'return_format' => 'id',
                    'add_term' => 1,
                    'save_terms' => 0,
                    'load_terms' => 0,
                    'field_type' => 'select',
                    'allow_null' => 0,
                    'allow_in_bindings' => 0,
                    'bidirectional' => 0,
                    'multiple' => 0,
                    'wrapper' => [
                        'width' => '50%',
                        'class' => '',
                        'id' => '',
                    ],
                ],
                [
                    'key' => 'field_64jhfhjjg9863bi',
                    'label' => __('Video post tag', APP_THEME_DOMAIN),
                    'name' => 'video_post_tag',
                    'aria-label' => '',
                    'type' => 'taxonomy',
                    'taxonomy' => 'post_tag',
                    'instructions' => __('Posts with this tag will be considered video posts.', APP_THEME_DOMAIN),
                    'return_format' => 'id',
                    'add_term' => 1,
                    'save_terms' => 0,
                    'load_terms' => 0,
                    'field_type' => 'select',
                    'allow_null' => 0,
                    'allow_in_bindings' => 0,
                    'bidirectional' => 0,
                    'multiple' => 0,
                    'wrapper' => [
                        'width' => '50%',
                        'class' => '',
                        'id' => '',
                    ],
                ],
                [
                    'key' => 'field_64jhflapod094563bi',
                    'label' => __('Gallery post tag', APP_THEME_DOMAIN),
                    'name' => 'gallery_post_tag',
                    'aria-label' => '',
                    'type' => 'taxonomy',
                    'instructions' => __('Posts with this tag will be considered gallery posts.', APP_THEME_DOMAIN),
                    'taxonomy' => 'post_tag',
                    'return_format' => 'id',
                    'add_term' => 1,
                    'save_terms' => 0,
                    'load_terms' => 0,
                    'field_type' => 'select',
                    'allow_null' => 0,
                    'allow_in_bindings' => 0,
                    'bidirectional' => 0,
                    'multiple' => 0,
                    'wrapper' => [
                        'width' => '50%',
                        'class' => '',
                        'id' => '',
                    ],
                ],
                [
                    'key' => 'field_94ik094563bi',
                    'label' => __('Behind the scenes tag', APP_THEME_DOMAIN),
                    'name' => 'bts_post_tag',
                    'aria-label' => '',
                    'type' => 'taxonomy',
                    'instructions' => __('Posts with this tag will be considered behind the scenes posts.', APP_THEME_DOMAIN),
                    'taxonomy' => 'post_tag',
                    'return_format' => 'id',
                    'add_term' => 1,
                    'save_terms' => 0,
                    'load_terms' => 0,
                    'field_type' => 'select',
                    'allow_null' => 0,
                    'allow_in_bindings' => 0,
                    'bidirectional' => 0,
                    'multiple' => 0,
                    'wrapper' => [
                        'width' => '50%',
                        'class' => '',
                        'id' => '',
                    ],
                ],
                [
                    'key' => 'field_94iklfo8849',
                    'label' => __('Private gallery tag', APP_THEME_DOMAIN),
                    'name' => 'private_gallery_post_tag',
                    'aria-label' => '',
                    'type' => 'taxonomy',
                    'instructions' => __('Posts with this tag will be considered private galleries.', APP_THEME_DOMAIN),
                    'taxonomy' => 'post_tag',
                    'return_format' => 'id',
                    'add_term' => 1,
                    'save_terms' => 0,
                    'load_terms' => 0,
                    'field_type' => 'select',
                    'allow_null' => 0,
                    'allow_in_bindings' => 0,
                    'bidirectional' => 0,
                    'multiple' => 0,
                    'wrapper' => [
                        'width' => '50%',
                        'class' => '',
                        'id' => '',
                    ],
                ],
                [
                    'key' => 'field_67aa49068si3b6',
                    'label' => __('Elementor', APP_THEME_DOMAIN),
                    'name' => '',
                    'aria-label' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'wpml_cf_preferences' => 1,
                    'placement' => 'left',
                    'endpoint' => 0,
                    'selected' => 0,
                ],
                [
                    'key' => 'field_67aa492kshufd7',
                    'label' => __('Product template', APP_THEME_DOMAIN),
                    'name' => 'pay_per_post_product_template',
                    'aria-label' => '',
                    'type' => 'post_object',
                    'post_type' => [
                        0 => 'elementor_library',
                    ],
                    'return_format' => 'id',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ],
                    'wpml_cf_preferences' => 2,
                    'default_value' => '',
                ],
            ],
            'location' => [
                [
                    [
                        'param' => 'options_page',
                        'operator' => '==',
                        'value' => 'mariana-erato',
                    ],
                ],
            ],
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => true,
            'description' => '',
            'show_in_rest' => 0,
            'acfml_field_group_mode' => 'translation',
        ]);
    }
}
